title: The Course
tagline: A brand new course on Learning Lab
description: Description of The Course
template:
  repo: the-course-template
  name: the-course
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
